--
--Table DDL
--
CREATE TABLE HZGJ.GJ_CONFIG
(
    ID bigint NOT NULL AUTO_INCREMENT,
    CONFIG_NAME character varying(100) ,
    CONFIG text ,
    TASK_ID bigint ,
    DETAIL_ID bigint ,
    IS_DEFAULT integer DEFAULT 0 ,
    CONSTRAINT GJ_CONFIG_PK PRIMARY KEY (ID)
) AUTO_INCREMENT=2
 BINLOG ON ;
--Table Comment
COMMENT ON TABLE HZGJ.GJ_CONFIG IS '配置表';
COMMENT ON COLUMN HZGJ.GJ_CONFIG.CONFIG_NAME IS '配置名称';
COMMENT ON COLUMN HZGJ.GJ_CONFIG.CONFIG IS '配置内容';
COMMENT ON COLUMN HZGJ.GJ_CONFIG.TASK_ID IS '任务id';
COMMENT ON COLUMN HZGJ.GJ_CONFIG.DETAIL_ID IS '任务详情id';
COMMENT ON COLUMN HZGJ.GJ_CONFIG.IS_DEFAULT IS '默认配置标记';

--Indexes DDL
CREATE UNIQUE INDEX GJ_CONFIG_PK ON HZGJ.GJ_CONFIG USING BTREE(ID) TABLESPACE SYSTEM INIT 64K NEXT 64K MAXSIZE UNLIMITED FILL 70 SPLIT 50;
CREATE TABLE HZGJ.GJ_LOG
(
    ID bigint NOT NULL AUTO_INCREMENT,
    TRACK_ID character varying(100) ,
    ORDER_TYPE character varying(64) ,
    LOG_TYPE character varying(64) ,
    LOG_TIME timestamp without time zone ,
    LOG_DETAIL text ,
    CODE character varying(100) ,
    CONSTRAINT GJ_LOG_PK PRIMARY KEY (ID)
) AUTO_INCREMENT=377
 BINLOG ON ;
--Table Comment
COMMENT ON TABLE HZGJ.GJ_LOG IS '日志记录表';
COMMENT ON COLUMN HZGJ.GJ_LOG.TRACK_ID IS 'OrderID 订单号';
COMMENT ON COLUMN HZGJ.GJ_LOG.ORDER_TYPE IS '订单类型: user_face 、data_driver';
COMMENT ON COLUMN HZGJ.GJ_LOG.LOG_TYPE IS '日志类型 Progress、Result';
COMMENT ON COLUMN HZGJ.GJ_LOG.LOG_TIME IS '日志产生时间';
COMMENT ON COLUMN HZGJ.GJ_LOG.LOG_DETAIL IS '日志详情';
COMMENT ON COLUMN HZGJ.GJ_LOG.CODE IS '日志编码';

--Indexes DDL
CREATE UNIQUE INDEX GJ_LOG_ID_UINDEX ON HZGJ.GJ_LOG USING BTREE(ID) TABLESPACE SYSTEM INIT 64K NEXT 64K MAXSIZE UNLIMITED FILL 70 SPLIT 50;
CREATE UNIQUE INDEX GJ_LOG_PK ON HZGJ.GJ_LOG USING BTREE(ID) TABLESPACE SYSTEM INIT 64K NEXT 64K MAXSIZE UNLIMITED FILL 70 SPLIT 50;
CREATE TABLE HZGJ.GJ_TASK
(
    ID bigint NOT NULL AUTO_INCREMENT,
    TASK_NAME character varying(100) ,
    ORDER_PATH text ,
    CREATE_DATE timestamp without time zone ,
    UPDATE_DATE timestamp without time zone ,
    CUR_WARN_LEVEL integer DEFAULT -1 ,
    MAX_WARN_LEVEL integer DEFAULT -1 ,
    CHECKED_DETAIL_ID bigint ,
    TASK_STATUS integer DEFAULT 1 ,
    CONSTRAINT GJ_TASK_PK PRIMARY KEY (ID)
) AUTO_INCREMENT=5
 BINLOG ON ;
--Table Comment
COMMENT ON TABLE HZGJ.GJ_TASK IS '任务表';
COMMENT ON COLUMN HZGJ.GJ_TASK.TASK_NAME IS '任务名称或者主卫星ID';
COMMENT ON COLUMN HZGJ.GJ_TASK.ORDER_PATH IS '订单文件磁盘路径';
COMMENT ON COLUMN HZGJ.GJ_TASK.CREATE_DATE IS '创建时间、启动时间';
COMMENT ON COLUMN HZGJ.GJ_TASK.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN HZGJ.GJ_TASK.CUR_WARN_LEVEL IS '当前告警等级';
COMMENT ON COLUMN HZGJ.GJ_TASK.MAX_WARN_LEVEL IS '历史最高危险等级';
COMMENT ON COLUMN HZGJ.GJ_TASK.CHECKED_DETAIL_ID IS '选中的规避策略';
COMMENT ON COLUMN HZGJ.GJ_TASK.TASK_STATUS IS '任务状态（执行中、已结束）';

--Indexes DDL
CREATE INDEX GJ_TASK_IDX_CUR_WARN_LEVEL ON HZGJ.GJ_TASK USING BTREE(CUR_WARN_LEVEL) TABLESPACE SYSTEM INIT 2M NEXT 4M MAXSIZE UNLIMITED FILL 70 SPLIT 50;
CREATE INDEX GJ_TASK_IDX_MAX_WARN_LEVEL ON HZGJ.GJ_TASK USING BTREE(MAX_WARN_LEVEL) TABLESPACE SYSTEM INIT 2M NEXT 4M MAXSIZE UNLIMITED FILL 70 SPLIT 50;
CREATE INDEX GJ_TASK_IDX_TASK_NAME ON HZGJ.GJ_TASK USING BTREE(TASK_NAME) TABLESPACE SYSTEM INIT 2M NEXT 4M MAXSIZE UNLIMITED FILL 70 SPLIT 50;
CREATE UNIQUE INDEX GJ_TASK_PK ON HZGJ.GJ_TASK USING BTREE(ID) TABLESPACE SYSTEM INIT 64K NEXT 64K MAXSIZE UNLIMITED FILL 70 SPLIT 50;
CREATE TABLE HZGJ.GJ_TASK_DETAILS
(
    ID bigint NOT NULL AUTO_INCREMENT,
    TASK_ID bigint NOT NULL,
    ORDER_PATH text ,
    TASK_NAME character varying(22) ,
    WARN_LEVEL integer DEFAULT -1 ,
    MENACE_SOURCE character varying(100) ,
    TASK_TYPE integer DEFAULT 0 ,
    RUN_PARAMS text ,
    TARGET_DETAILS text ,
    STRATEGY text ,
    CREATE_TIME timestamp without time zone ,
    CONSTRAINT GJ_TASK_DETAILS_PK PRIMARY KEY (ID),
    CONSTRAINT GJ_TASK_DETAILS_GJ_TASK_FK FOREIGN KEY (TASK_ID) REFERENCES HZGJ.GJ_TASK(ID)
) AUTO_INCREMENT=146
 BINLOG ON ;
--Table Comment
COMMENT ON TABLE HZGJ.GJ_TASK_DETAILS IS '任务详情表';
COMMENT ON COLUMN HZGJ.GJ_TASK_DETAILS.ID IS '任务详情表ID';
COMMENT ON COLUMN HZGJ.GJ_TASK_DETAILS.TASK_ID IS '任务表ID';
COMMENT ON COLUMN HZGJ.GJ_TASK_DETAILS.ORDER_PATH IS '任务路径';
COMMENT ON COLUMN HZGJ.GJ_TASK_DETAILS.TASK_NAME IS '任务名称或者主目标ID';
COMMENT ON COLUMN HZGJ.GJ_TASK_DETAILS.WARN_LEVEL IS '告警等级';
COMMENT ON COLUMN HZGJ.GJ_TASK_DETAILS.MENACE_SOURCE IS '威胁来源';
COMMENT ON COLUMN HZGJ.GJ_TASK_DETAILS.TASK_TYPE IS '任务来源、类型（自动，手动）';
COMMENT ON COLUMN HZGJ.GJ_TASK_DETAILS.RUN_PARAMS IS '运行参数';
COMMENT ON COLUMN HZGJ.GJ_TASK_DETAILS.TARGET_DETAILS IS '目标详情（before和arter 两个文件路径）';
COMMENT ON COLUMN HZGJ.GJ_TASK_DETAILS.STRATEGY IS '规避策略';
COMMENT ON COLUMN HZGJ.GJ_TASK_DETAILS.CREATE_TIME IS '创建时间';

--Indexes DDL
CREATE UNIQUE INDEX GJ_TASK_DETAILS_PK ON HZGJ.GJ_TASK_DETAILS USING BTREE(ID) TABLESPACE SYSTEM INIT 64K NEXT 64K MAXSIZE UNLIMITED FILL 70 SPLIT 50;
CREATE TABLE HZGJ.GJ_TASK_RESULT
(
    ID bigint NOT NULL AUTO_INCREMENT,
    ORDER_ID character varying(255) ,
    TASK_STATUS character varying(100) ,
    SCAN_INTERVAL bigint ,
    ORBIT_WARN_LEVEL integer ,
    LASER_WARN_LEVEL integer ,
    P_ID bigint DEFAULT 0 NOT NULL,
    CREATE_DATE timestamp without time zone ,
    "ORDER" clob ,
    STRATEGY clob ,
    CHART clob ,
    WORK_PATH character varying(500) ,
    OUTPUT_PATH character varying(500) ,
    SATELLITE_ID character varying(100) ,
    UPDATE_DATE timestamp without time zone ,
    ALARMS clob ,
    PATH_GBCL_XML clob ,
    CONSTRAINT GJ_TASK_RESULT_PK PRIMARY KEY (ID)
) AUTO_INCREMENT=8
 BINLOG ON ;
--Table Comment
COMMENT ON TABLE HZGJ.GJ_TASK_RESULT IS '任务结果';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.ID IS 'ID';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.ORDER_ID IS '任务名称或者任务ID';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.TASK_STATUS IS '任务状态  working 工作中、finished 结束';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.SCAN_INTERVAL IS '任务扫描间隔';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.ORBIT_WARN_LEVEL IS '轨道接近当前告警等级 0、1、2、3';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.LASER_WARN_LEVEL IS '激光告警当前告警等级 0、1、2、3';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.P_ID IS '父级ID';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT."ORDER" IS '订单内容';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.STRATEGY IS '策略';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.CHART IS '图标';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.WORK_PATH IS '订单输入路径';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.OUTPUT_PATH IS '订单结果输出路径';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.SATELLITE_ID IS '卫星ID';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.UPDATE_DATE IS '更新时间';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.ALARMS IS '告警数据列表';
COMMENT ON COLUMN HZGJ.GJ_TASK_RESULT.PATH_GBCL_XML IS 'XML数据';

--Indexes DDL
CREATE UNIQUE INDEX GJ_TASK_RESULT_PK ON HZGJ.GJ_TASK_RESULT USING BTREE(ID) TABLESPACE SYSTEM INIT 64K NEXT 64K MAXSIZE UNLIMITED FILL 70 SPLIT 50;
CREATE TABLE HZGJ.GJ_WARN_RESULT
(
    ID bigint NOT NULL AUTO_INCREMENT,
    TASK_ID bigint NOT NULL,
    SATELLITE_ID character varying(100) ,
    ORDER_ID character varying(100) ,
    WARN_TYPE character varying(100) ,
    WARN_LEVEL integer ,
    WARN_TIME_UTC timestamp without time zone ,
    WARN_INFO character varying(500) ,
    TARGET_ID character varying(100) ,
    WARN_STATUS integer ,
    CREATE_TIME timestamp without time zone ,
    CONSTRAINT GJ_WARN_RESULT_PK PRIMARY KEY (ID),
    CONSTRAINT GJ_WARN_RESULT_GJ_TASK_RESULT_FK FOREIGN KEY (TASK_ID) REFERENCES HZGJ.GJ_TASK_RESULT(ID)
)
    BINLOG ON ;
--Table Comment
COMMENT ON COLUMN HZGJ.GJ_WARN_RESULT.ID IS 'ID';
COMMENT ON COLUMN HZGJ.GJ_WARN_RESULT.TASK_ID IS '任务ID';
COMMENT ON COLUMN HZGJ.GJ_WARN_RESULT.SATELLITE_ID IS '卫星ID';
COMMENT ON COLUMN HZGJ.GJ_WARN_RESULT.ORDER_ID IS '任务名称';
COMMENT ON COLUMN HZGJ.GJ_WARN_RESULT.WARN_TYPE IS '告警类型 laser ';
COMMENT ON COLUMN HZGJ.GJ_WARN_RESULT.WARN_LEVEL IS '告警等级';
COMMENT ON COLUMN HZGJ.GJ_WARN_RESULT.WARN_TIME_UTC IS '告警时间';
COMMENT ON COLUMN HZGJ.GJ_WARN_RESULT.WARN_INFO IS '告警信息';
COMMENT ON COLUMN HZGJ.GJ_WARN_RESULT.TARGET_ID IS '威胁来源';
COMMENT ON COLUMN HZGJ.GJ_WARN_RESULT.WARN_STATUS IS '告警状态   0 未归档  1 已归档';
COMMENT ON COLUMN HZGJ.GJ_WARN_RESULT.CREATE_TIME IS '创建时间';

--Indexes DDL
CREATE UNIQUE INDEX GJ_WARN_RESULT_PK ON HZGJ.GJ_WARN_RESULT USING BTREE(ID) TABLESPACE SYSTEM INIT 64K NEXT 64K MAXSIZE UNLIMITED FILL 70 SPLIT 50;
