server:
  port: 8009
  servlet:
    context-path: /gj
    jsp:
      init-parameters:
        listings: true
  shutdown: graceful

spring:
  application:
    name: display
  lifecycle:
    timeout-per-shutdown-phase: 10s
  config:
    activate:
      on-profile: local
  datasource:
    druid:
      driver-class-name: com.oscar.Driver
      #      url: jdbc:oscar://192.168.1.14:2003/OSRDB?serverTimezone=UTC&useSSL=FALSE
      url: jdbc:oscar://192.168.43.236:2003/OSRDB?serverTimezone=UTC&useSSL=FALSE
#      url: jdbc:oscar://192.168.0.103:2003/OSRDB?serverTimezone=UTC&useSSL=FALSE
      #      username: SYSDBA
      username: DSUSER
      #      password: szoscar55
      password: 123456
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      # 配置初始化大小、最小、最大 (通常来说，只需要修改initialSize、minIdle、maxActive)
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 30000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      validation-query: 'SELECT 1 FROM dual'
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      write-dates-as-timestamps: true
  rabbitmq:
    username: hzgj
    password: hzgj123456
#    host: 192.168.43.244
    host: 192.168.43.244
    port: 5672
    virtual-host: hzgj
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.yhl.gl.mapper: DEBUG
# mybatis-plus 配置
mybatis-plus:
  global-config:
    banner: off
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
# mybatis 分页插件
pagehelper:
  auto-dialect: true




# python 程序相关配置
pyScript:
  # 脚本工作目录
  pyWorkDir: warningProgram/core
  # 主脚本
  path: warning_main.py
  outputPath: ./output/
pyConfig:
  warning_gates_path: warningProgram/core/param/G20210101_warning_gates.json
  c_lib_param_path: warningProgram/core/settings/c_lib_param.json
# 配置参数的存放路径，读取路径下的json和txt文件路径，供前端浏览选择
paramDirConfig:
  paramLEAP_Path: /Users/shishifanbuxie/FTP/temp
  paramEOP_Path: /Users/shishifanbuxie/FTP/local
  paramSWD_Path: /Users/shishifanbuxie/FTP/displayPlaybackslist
  paramERR_Path: /Users/shishifanbuxie/FTP/2021-03-26
#!!!==加上参数u让脚本实时输出==!!!
pyCmd:
  param_list: python3,-u,${pyScript.path}
#日志正则匹配(处理)
pyLog:
  regex_pattern: '\[(.+) @ (\d+-\d+-\d+ \d+:\d+:\d+.\d+)\] \[code=(\d+)\] (.+)'




#=================task相关配置===============
task:
  enableResume: true                         # 程序重启后是否恢复执行之前的任务,默认执行，设置 false 不执行
  finishedFileFlag: "end.txt"                 # 文件夹内任务结束标志，扫描到该文件，则结束任务
  period: 60000                                # 任务运行时间间隔，单位毫秒
  orderRunParam:
    savePath: warningProgram/historyRunParam     # 订单运行参数保存路径
    createDirByDay: true                           # 是否按天分文件夹  如果是，则 savePath = warningProgram/historyRunParam/2022-08-01 这种
    createDirByTask: true                       # 是否按任务分文件夹  如果是  则savePath = warningProgram/historyRunParam/任务xx 这种，如果按天也开了，savePath=warningProgram/historyRunParam/2022-08-01/任务xx 这种
  defaultParam: # 默认参数
    flushToDBOnStart: true                   # 程序启动时，是否刷新数据库中的默认配置
    #    path: config/defaultParam.json            # 默认配置路径(部署)
    path: defaultParam.json            # 默认配置路径(开发)


# (inputFiles)输入文件后缀配置
suffixFilter:
  # 主卫星输入文件后缀
  satelliteFile: sat
  # 目标轨道数据文件后缀
  targetOrbit: obt
  # 目标雷达轨道文件后缀
  targetRadar: rae
  # 目标激光数据文件后缀
  targetLaser: las
  # 观测质量评估
  obs_GTW: GTW
  obs_EPH: txt

# 测试订单数据（测试用，给定指定时间）
testOrder:
  enable: true
  startUTC: 2020, 11, 28, 00, 00, 00